<a href="https://colab.research.google.com/github/thucuyen127/Thang/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import random

def taomatran(m,n): #Hàm tạo ma trận m hàng n cột
  a = np.random.randint(-10,10,(m,n))
  return a
m=int(input('m = '))
n=int(input('n = '))
p=int(input('p = '))
a = taomatran(m,n)
b = taomatran(n,p)
c = taomatran(m,n)
print('A = \n',a)
print('B = \n',b)
print('C = \n',c)
print('A + C = \n',a + c)
print('A - C = \n',a - c)
print('A * B = \n',a @ b)
print('A / C = \n',a  @ np.linalg.matrix_power(c, -1))
print('A * 5 = \n',a * 5)
print('A / 5 = \n',a / 5)
print('ma tran chuyen vi cua A:\n',np.transpose(a))


m = 3
n = 3
p = 5
A = 
 [[  6  -3 -10]
 [ -8  -1  -7]
 [  7   9   1]]
B = 
 [[ -5   8   2  -8   6]
 [  7   0  -8   3   2]
 [-10   5   7   4  -8]]
C = 
 [[-6 -9  2]
 [ 5  6 -8]
 [-4 -8 -7]]
A + C = 
 [[  0 -12  -8]
 [ -3   5 -15]
 [  3   1  -6]]
A - C = 
 [[ 12   6 -12]
 [-13  -7   1]
 [ 11  17   8]]
A * B = 
 [[ 49  -2 -34 -97 110]
 [103 -99 -57  33   6]
 [ 18  61 -51 -25  52]]
A / C = 
 [[-677. -504.  384.]
 [ 893.  666. -505.]
 [-155. -115.   87.]]
A * 5 = 
 [[ 30 -15 -50]
 [-40  -5 -35]
 [ 35  45   5]]
A / 5 = 
 [[ 1.2 -0.6 -2. ]
 [-1.6 -0.2 -1.4]
 [ 1.4  1.8  0.2]]
ma tran chuyen vi cua A:
 [[  6  -8   7]
 [ -3  -1   9]
 [-10  -7   1]]
